#!/usr/bin/env bash
#
# Update a Jekyll post's date.
#
# P.S.: the `date` command is *lovely*. formatting is simply ezpz.
#

# regex pattern to look for
# the first line containing this is replaced with the current datetime
pattern="^date:"

if [ ! -f "$1" ]; then
    echo "error: not a file"
    exit 1
fi

file="$1"

# check for frontmatter separator line
if [ "$(head -n1 "$file")" != "---" ]; then
    echo "error: not a Jekyll post (no frontmatter)"
    exit 2
fi

old_datetime=$(grep -m1 --color=never "date: " "$file" | cut -d " " --complement -f 1)
cur_date="$(date "+%Y-%m-%d")"
cur_time="$(date "+%H:%M:%S")"

sed -i "0,/${pattern}.*/s//date: $cur_date $cur_time/" "$file"

# echo change made
echo "$old_datetime -> $cur_date $cur_time"

# see if the filename needs updating
old_namedate="$(cut -d "-" -f 1,2,3 <<< "$file")"
old_nametitle="$(cut -d "-" -f 1,2,3 --complement <<< "$file")"
if [ "$old_namedate" != "$cur_date" ]; then
    mv "$file" "$cur_date-$old_nametitle"

    # echo change made
    echo "$file -> $cur_date-$old_nametitle"
fi
